name = "remix-cloudflare-workers-template"

main = "./server.ts"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2024-09-02"

# https://developers.cloudflare.com/workers/static-assets/binding/
[assets]
directory = "./build/client"

[build]
command = "npm run build"

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true